import { useEffect, useMemo, useState } from 'react';
import { archiveAccessProfile, copyAccessProfile, createAccessProfile, getAccessProfiles, getPermissions, previewAccessProfileSync, syncAccessProfile, updateAccessProfile } from '../api';
import type { AccessProfileItem, AdminCompanyListItem, PermissionItem } from '../types';
import { Alert, Badge, Button, Card, ErrorState, FormGroup, Input, Modal, Select, Table } from '../components/ui';

export function AdminAccessPage({ token, companies }: { token: string; companies: AdminCompanyListItem[] }) {
  const [profiles, setProfiles] = useState<AccessProfileItem[]>([]); const [permissions, setPermissions] = useState<PermissionItem[]>([]);
  const [companyFilter, setCompanyFilter] = useState('templates'); const [editing, setEditing] = useState<AccessProfileItem | null>(null); const [open, setOpen] = useState(false);
  const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
  const [form, setForm] = useState({ company_id: '', name: '', description: '', data_scope: 'company' as 'own'|'company', permissions: [] as string[] });
  async function load() { try { const [p, perms] = await Promise.all([getAccessProfiles(token, 'active=1'), getPermissions(token)]); setProfiles(p); setPermissions(perms); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao carregar perfis.'); } }
  useEffect(() => { void load(); }, [token]);
  const visible = profiles.filter((p) => companyFilter === 'templates' ? p.company_id === null : String(p.company_id) === companyFilter);
  const groups = useMemo(() => Object.entries(permissions.reduce<Record<string, PermissionItem[]>>((acc, permission) => { (acc[permission.group_name] ||= []).push(permission); return acc; }, {})), [permissions]);
  function start(profile?: AccessProfileItem) { setEditing(profile ?? null); setForm(profile ? { company_id: String(profile.company_id ?? ''), name: profile.name, description: profile.description ?? '', data_scope: profile.data_scope, permissions: profile.permissions } : { company_id: companyFilter === 'templates' ? '' : companyFilter, name: '', description: '', data_scope: 'company', permissions: [] }); setOpen(true); }
  async function save(e: React.FormEvent) { e.preventDefault(); try { if (editing) await updateAccessProfile(token, editing.id, { name: form.name, description: form.description, data_scope: form.data_scope, permissions: form.permissions }); else await createAccessProfile(token, { company_id: form.company_id ? Number(form.company_id) : null, name: form.name, description: form.description, data_scope: form.data_scope, permissions: form.permissions }); setOpen(false); setSuccess('Perfil salvo. Alterações globais não foram propagadas automaticamente.'); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Falha ao salvar perfil.'); } }
  async function copy(profile: AccessProfileItem) { const companyId = window.prompt('Código da clínica que receberá uma cópia deste modelo:'); if (!companyId) return; try { await copyAccessProfile(token, profile.id, [Number(companyId)]); setSuccess('Modelo copiado para a clínica.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao copiar.'); } }
  async function applyVersion(profile: AccessProfileItem) { const companyId = window.prompt('Código da clínica que terá a cópia atualizada:'); if (!companyId) return; try { const preview = await previewAccessProfileSync(token, profile.id, [Number(companyId)]); const impact = preview.data[0]; if (!impact?.profile_id) { setError('Essa clínica ainda não possui uma cópia deste modelo. Use “Copiar para clínica”.'); return; } if (!window.confirm(`Atualizar ${impact.company_name} da versão ${impact.current_version} para ${impact.target_version}? ${impact.affected_users} usuário(s) serão afetados.`)) return; await syncAccessProfile(token, profile.id, [Number(companyId)]); setSuccess('Nova versão aplicada explicitamente à clínica.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao aplicar versão.'); } }
  async function archive(profile: AccessProfileItem) { if (!window.confirm(`Arquivar o perfil ${profile.name}?`)) return; try { await archiveAccessProfile(token, profile.id); setSuccess('Perfil arquivado.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao arquivar.'); } }
  return <>
    <Card><div className="lw-flex-between"><div><h2>Controle de acesso</h2><p>Modelos globais são blueprints; cópias das clínicas só mudam por aplicação explícita.</p></div><Button onClick={() => start()}>Novo perfil</Button></div>
      <FormGroup label="Escopo" ><Select value={companyFilter} onChange={(e) => setCompanyFilter(e.target.value)}><option value="templates">Modelos globais</option>{companies.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</Select></FormGroup></Card>
    {success ? <Alert variant="success">{success}</Alert> : null}{error ? <ErrorState message={error}/> : null}
    <Table><thead><tr><th>Perfil</th><th>Escopo de dados</th><th>Versão</th><th>Permissões</th><th>Usuários</th><th>Ações</th></tr></thead><tbody>{visible.map((profile) => <tr key={profile.id}>
      <td><strong>{profile.name}</strong><br/><small>{profile.description}</small>{profile.is_system ? <><br/><Badge variant="info">Protegido</Badge></> : null}</td><td>{profile.data_scope === 'own' ? 'Próprios dados' : 'Clínica inteira'}</td><td>{profile.version}</td><td>{profile.is_full_access ? 'Acesso total' : `${profile.permissions.length} permissões`}</td><td>{profile.users_count}</td>
      <td><div className="lw-flex-wrap-gap">{!profile.is_system ? <Button variant="secondary" onClick={() => start(profile)}>Editar</Button> : null}{profile.company_id === null ? <><Button variant="secondary" onClick={() => void copy(profile)}>Copiar para clínica</Button><Button variant="secondary" onClick={() => void applyVersion(profile)}>Aplicar versão</Button></> : null}{!profile.is_system ? <Button variant="secondary" onClick={() => void archive(profile)}>Arquivar</Button> : null}</div></td>
    </tr>)}</tbody></Table>
    <Modal open={open} onClose={() => setOpen(false)} title={editing ? 'Editar perfil' : 'Novo perfil'}><form onSubmit={save} className="lw-stack">
      {!editing ? <FormGroup label="Destino"><Select value={form.company_id} onChange={(e) => setForm({...form, company_id:e.target.value})}><option value="">Modelo global</option>{companies.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></FormGroup> : null}
      <FormGroup label="Nome"><Input required value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></FormGroup><FormGroup label="Descrição"><Input value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></FormGroup>
      <FormGroup label="Alcance dos dados"><Select value={form.data_scope} onChange={(e)=>setForm({...form,data_scope:e.target.value as 'own'|'company'})}><option value="company">Clínica inteira</option><option value="own">Somente dados próprios</option></Select></FormGroup>
      {groups.map(([group, items]) => <Card key={group}><strong>{group}</strong>{items.map((permission)=><label key={permission.code} className="lw-checkbox-row"><input type="checkbox" checked={form.permissions.includes(permission.code)} onChange={(e)=>setForm({...form,permissions:e.target.checked?[...form.permissions,permission.code]:form.permissions.filter((p)=>p!==permission.code)})}/><span>{permission.name}</span></label>)}</Card>)}
      <Button type="submit">Salvar perfil</Button>
    </form></Modal>
  </>;
}
